#Version de nuestro archivo
version: 'v2.21.0'

services:

  postgreSQL:
    image: postgres:16
    container_name: psql
    restart: always    
    env_file:
      - .env
    environment:       
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT_PC}:${POSTGRES_PORT}

  pgadmin4:
    image: dpage/pgadmin4:8.3
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: coderjocs@dominio.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
